import { Changa } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/navigation/NavBar";

const changa = Changa({
  subsets: ["arabic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" data-theme="mytheme" className="bg-bg">
      <body className={`${changa.className} antialiase text-white`}>
        <NavBar /> {children}
      </body>
    </html>
  );
}
